[server]
enableStaticServing = true

[theme]
base = "dark"
primaryColor = "#1DB954"                   
backgroundColor = "#191414"               
secondaryBackgroundColor = "#282828"       
textColor = "#FFFFFF"         
linkColor = "#1DB954"
borderColor = "#282828" 
showWidgetBorder = true
showSidebarBorder = false
font = "GothamBook"
headingFont = "Gotham-Bold"

[[theme.fontFaces]]
family = "GothamBook"
url = "app/static/GothamBook.ttf"
weight = 400
style = "normal"

[[theme.fontFaces]]
family = "Gotham-Bold"
url = "app/static/Gotham-Bold.otf"
weight = 700
style = "normal"