[server]
enableStaticServing = true

[client]
showSidebarNavigation = false

[theme]
base = "dark"
primaryColor = "#1DB954"                   
backgroundColor = "#191414"               
secondaryBackgroundColor = "#282828"       
textColor = "#FFFFFF"         
linkColor = "#1DB954"
borderColor = "#282828" 
showWidgetBorder = true
showSidebarBorder = false
font = "GothamBook"
headingFont = "GothamBold"

[[theme.fontFaces]]
family = "GothamBook"
url = "app/static/GothamBook.ttf"
weight = 400
style = "normal"

[[theme.fontFaces]]
family = "GothamBold"
url = "app/static/GothamBold.ttf"
weight = 700
style = "normal"