[server]
enableStaticServing = true

[theme]
base = "dark"
primaryColor = "#1DB954"                   
backgroundColor = "#191414"               
secondaryBackgroundColor = "#282828"       
textColor = "#FFFFFF"                       
linkColor = "#1DB954"                       
font = "Gotham-Book, monospace"              
headingFont = "Gotham-Bold, monospace"      
baseRadius = 2                               
borderColor = "#282828"                      
showWidgetBorder = true
baseFontSize = 14
showSidebarBorder = false

[[theme.fontFaces]]
font = "Gotham-Bold"
url = "app/static/Gotham-Bold.otf"
weight = 700
style = "normal"

[[theme.fontFaces]]
font = "Gotham-Book"
url = "app/static/GothamBook.ttf"
weight = 400
style = "normal"